# Generated by Django 3.0.8 on 2021-05-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0003_auto_20210511_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Covid_image',
        ),
    ]
